feature/RMA-92081: checkin on behalf of vishal( grid link button changes)
assureclaims/halstack-angular pull request #59
Opened 2021-11-30 15:35 UTC by Shivam3266

2021-11-30 15:42 UTC, assureclaims commented on projects/dxc-ngx-cdk/src/lib/dxc-crud-table/dxc-crud-cell-render/dxc-crud-cell-render.component.html
> +        <span [ngClass]="formatColumns[columnName].type == 'button' ? formatColumns[columnName].class : ''" [innerHtml]="rowData[columnName] | formatter:formatColumns[columnName]"></span>
The class should be on button tag

2021-11-30 15:44 UTC, assureclaims requested changes

2021-11-30 15:44 UTC, assureclaims commented on projects/dxc-ngx-cdk/src/lib/dxc-crud-table/dxc-crud-cell-render/dxc-crud-cell-render.component.scss
> +{
Css should be on ur app component

2021-12-01 13:55 UTC, Shivam3266 commented on projects/dxc-ngx-cdk/src/lib/dxc-crud-table/dxc-crud-cell-render/dxc-crud-cell-render.component.html
> +<ng-template #elseif1>
done

2021-12-01 13:55 UTC, Shivam3266 commented on projects/dxc-ngx-cdk/src/lib/dxc-crud-table/dxc-crud-cell-render/dxc-crud-cell-render.component.html
> +        <span [ngClass]="formatColumns[columnName].type == 'button' ? formatColumns[columnName].class : ''" [innerHtml]="rowData[columnName] | formatter:formatColumns[columnName]"></span>
done

2021-12-01 13:55 UTC, Shivam3266 commented on projects/dxc-ngx-cdk/src/lib/dxc-crud-table/dxc-crud-cell-render/dxc-crud-cell-render.component.scss
> +{
done

2021-12-02 07:06 UTC, assureclaims approved these changes

2021-12-02 07:06 UTC, merged